### PR TITLE
Content changes on tickets 323 324 337 338 339 343 363 382 383

### PR DESCRIPTION
**Pull request by tjbburton**
Minor content changes following [cds2-323](https://dsdmoj.atlassian.net/jira/software/c/projects/CDS2/boards/994/backlog?view=detail&selectedIssue=CDS2-323&issueLimit=100)

### CODE REVIEW

**Comment by tjbburton** [comment]
I will also add in the content changes for tickets 324, 338, 339 and 343 into this branch

**Comment by neil-stephen-mcgonigle** [comment]
Could you squash to one commit Tom, with a general commit message .

**Comment by tjbburton** [comment]
Now also includes ticket CDS2-363

**Comment by stephenjmcneill1971** [comment]
Squash commits again

**Review by stephenjmcneill1971 — APPROVED** [review]

**Pull request merged**
